# Generated by Django 3.0.7 on 2020-08-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='completed_by',
        ),
        migrations.AddField(
            model_name='issue',
            name='volunteers',
            field=models.ManyToManyField(related_name='user_volunteers', to='home.User'),
        ),
    ]
